# Generated by Django 5.1.2 on 2025-03-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_image_teacher_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='img',
            new_name='image',
        ),
    ]
