# Generated by Django 5.1.2 on 2025-03-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_rename_img_teacher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
